import type { AlgCase, Algset } from '@/algsets/types'
import type { ToLetter } from '@/helpers/helpers'
import { SPEFFZ } from '@/algsets/commutators'
import { CORNER_OF } from '@/algsets/t2c'

// Parities: one alg swaps the corner buffer with a corner target and two
// edges with each other (memo swap / pseudo swap). Memoed as just the corner
// target letter — the edge swap is the group the case lives in. Data:
// parities_map.json, keyed "<corner buffer> <corner target> <edge1> <edge2>"
// (generated by scripts/fetch_blddb_parity_algs.mjs from blddb).
export interface RawParity {
  algs: string[]
}

// Path segments join stickers with this separator so each piece translates
// independently through the letter scheme.
const SEP = '·'

const lettersOf = (segment: string, toLetter: ToLetter): string =>
  segment.split(SEP).map(toLetter).join('')

const speffz = (s: string): string => SPEFFZ[s] ?? s

// The raw data names corner buffers canonically (DFR, DFL, DBL); the trainer
// shows those buffers as the sticker they're tracked by (RDF, FDL, LDB),
// consistent with the corner commutators' buffer order.
const BUFFER_STICKER: Record<string, string> = { DFR: 'RDF', DFL: 'FDL', DBL: 'LDB' }
const bufferSticker = (v: string): string => BUFFER_STICKER[v] ?? v

// Edge-swap groups: UF-UR (the standard pseudo swap) first, then the other
// swaps of the UF piece, then everything else — Speffz-ordered within.
const edgeSortKey = (e1: string, e2: string): string => {
  if (e1 === 'UF' && e2 === 'UR') return '0'
  const onUF = e1 === 'UF' || e1 === 'FU'
  return (onUF ? '1' : '2') + speffz(e1) + speffz(e2)
}

export const partition = (raw: Record<string, RawParity>, bufferOrder: string[]): AlgCase[] => {
  const rank = new Map(bufferOrder.map((b, i) => [CORNER_OF[b], i]))

  type Sortable = AlgCase & { _sort: [number, string, string] }
  const out: Sortable[] = []

  for (const [id, c] of Object.entries(raw)) {
    const [cb, ct, e1, e2] = id.split(' ')
    out.push({
      id,
      path: [cb, e1 + SEP + e2, ct],
      algs: c.algs,
      scrambles: [], // none pre-generated; makeScramble falls back to inverse algs
      _sort: [rank.get(CORNER_OF[cb]) ?? bufferOrder.length, edgeSortKey(e1, e2), speffz(ct)],
    })
  }

  out.sort((a, b) =>
    a._sort[0] - b._sort[0] ||
    a._sort[1].localeCompare(b._sort[1]) ||
    a._sort[2].localeCompare(b._sort[2]),
  )
  return out.map(({ _sort, ...rest }) => rest)
}

export const parities: Algset = {
  id: 'parities',
  name: 'algset.parities',
  usesLetterScheme: true,
  levels: [
    // Stufe 1: the corner buffer (as its tracked sticker), ordered by the
    // settings' buffer order.
    { id: 'buffer', display: (v, ctx) => ({ primary: bufferSticker(v), secondary: ctx.toLetter(bufferSticker(v)) }) },
    // Stufe 2: the edge swap ("UF-UR" first), with its letters as secondary.
    { id: 'edgeSwap', display: (v, ctx) => ({ primary: v.split(SEP).join('-'), secondary: lettersOf(v, ctx.toLetter) }) },
    // Stufe 3: the case — just the corner target letter.
    { id: 'case', display: (v, ctx) => ({ primary: ctx.toLetter(v) }) },
  ],
  load: () =>
    import('@/assets/parities_map.json').then(
      (m) => (m.default as unknown) as Record<string, RawParity>,
    ),
  derive: (raw, deps) => partition(raw as Record<string, RawParity>, deps.bufferOrder),
  caseLabel: (c, toLetter) => toLetter(c.path[2]),
  // The edge swap, shown small next to the letter (e.g. "A UF-UR").
  caseSecondary: (c) => c.path[1].split(SEP).join('-'),
  statsDisplay: (c, toLetter) => ({
    primary: toLetter(c.path[2]),
    secondary: `${bufferSticker(c.path[0])} ${c.path[1].split(SEP).join('-')}`,
  }),
  statsGroupFilter: true,
}
