import type { AlgCase, Algset } from '@/algsets/types'
import type { ToLetter } from '@/helpers/helpers'
import { SPEFFZ } from '@/algsets/commutators'
import { STICKER_CYCLES } from '@/algsets/t2c'

// Parities: one alg swaps the corner buffer with a corner target and two
// edges with each other (memo swap / pseudo swap). Memoed as just the corner
// target letter — the edge swap is the group the case lives in. Data:
// parities_map.json, keyed "<corner1> <corner2> <edge1> <edge2>"
// (generated by scripts/fetch_blddb_parity_algs.mjs from blddb). blddb has no
// buffer notion for parities: corner1/corner2 are just the two stickers of
// the corner swap, named canonically (U/D facelet first). Which corner is the
// buffer — and from which of its stickers the target is named — is derived
// at runtime from the configurable buffer order, like the commutator sets.
export interface RawParity {
  algs: string[]
  scrambles?: string[] // pre-generated by scripts/generate_parity_scrambles.mjs
}

// Path segments join stickers with this separator so each piece translates
// independently through the letter scheme.
const SEP = '·'

const lettersOf = (segment: string, toLetter: ToLetter): string =>
  segment.split(SEP).map(toLetter).join('')

const speffz = (s: string): string => SPEFFZ[s] ?? s

// The DBL corner is a valid parity buffer in the data (paired with DBR) but
// is never part of the configurable order, so its tracked sticker is appended
// with lowest priority — cf. EXTRA_CORNERS in flip_twist.ts.
const EXTRA_BUFFERS = ['LDB']

const cycleOf = (s: string) => STICKER_CYCLES.find((c) => c.includes(s))
const rot = (s: string, n: number): string => {
  const c = cycleOf(s)!
  return c[(c.indexOf(s) + n) % 3]
}

// The corner swap "c1 <-> c2" moves stickers rigidly: rot(c1, k) lands on
// rot(c2, k) and vice versa. A solver whose buffer sticker b sits on one of
// the two corners memos the image of b under that map — null if b is on
// neither corner.
const targetFrom = (b: string, c1: string, c2: string): string | null => {
  const cyc1 = cycleOf(c1)
  const cyc2 = cycleOf(c2)
  if (cyc1?.includes(b)) return rot(c2, (cyc1.indexOf(b) - cyc1.indexOf(c1) + 3) % 3)
  if (cyc2?.includes(b)) return rot(c1, (cyc2.indexOf(b) - cyc2.indexOf(c2) + 3) % 3)
  return null
}

// Edge-swap groups: UF-UR (the standard pseudo swap) first, then the other
// swaps of the UF piece, then everything else — Speffz-ordered within.
const edgeSortKey = (e1: string, e2: string): string => {
  if (e1 === 'UF' && e2 === 'UR') return '0'
  const onUF = e1 === 'UF' || e1 === 'FU'
  return (onUF ? '1' : '2') + speffz(e1) + speffz(e2)
}

export const partition = (raw: Record<string, RawParity>, bufferOrder: string[]): AlgCase[] => {
  const order = [...bufferOrder, ...EXTRA_BUFFERS.filter((b) => !bufferOrder.includes(b))]

  type Sortable = AlgCase & { _sort: [number, string, string] }
  const out: Sortable[] = []

  for (const [id, c] of Object.entries(raw)) {
    const [c1, c2, e1, e2] = id.split(' ')
    // buffer = the highest-priority buffer sticker on either swapped corner;
    // the target is re-anchored to that sticker (e.g. "DFR DFL": buffer RDF,
    // target FDL — not the canonical DFL).
    let buffer: string | null = null
    let target: string | null = null
    let bufIdx = 0
    for (; bufIdx < order.length; bufIdx++) {
      target = targetFrom(order[bufIdx], c1, c2)
      if (target !== null) { buffer = order[bufIdx]; break }
    }
    if (buffer === null || target === null) continue // no buffer on this swap

    out.push({
      id,
      path: [buffer, e1 + SEP + e2, target],
      algs: c.algs,
      scrambles: c.scrambles ?? [],
      _sort: [bufIdx, edgeSortKey(e1, e2), speffz(target)],
    })
  }

  out.sort((a, b) =>
    a._sort[0] - b._sort[0] ||
    a._sort[1].localeCompare(b._sort[1]) ||
    a._sort[2].localeCompare(b._sort[2]),
  )
  return out.map(({ _sort, ...rest }) => rest)
}

export const parities: Algset = {
  id: 'parities',
  name: 'algset.parities',
  usesLetterScheme: true,
  levels: [
    // Stufe 1: the corner buffer (its tracked sticker, e.g. UFR / RDF),
    // ordered by the settings' buffer order.
    { id: 'buffer', display: (v, ctx) => ({ primary: v, secondary: ctx.toLetter(v) }) },
    // Stufe 2: the edge swap ("UF-UR" first), with its letters as secondary.
    { id: 'edgeSwap', display: (v, ctx) => ({ primary: v.split(SEP).join('-'), secondary: lettersOf(v, ctx.toLetter) }) },
    // Stufe 3: the case — just the corner target letter.
    { id: 'case', display: (v, ctx) => ({ primary: ctx.toLetter(v) }) },
  ],
  load: () =>
    import('@/assets/parities_map.json').then(
      (m) => (m.default as unknown) as Record<string, RawParity>,
    ),
  derive: (raw, deps) => partition(raw as Record<string, RawParity>, deps.bufferOrder),
  caseLabel: (c, toLetter) => toLetter(c.path[2]),
  // The edge swap, shown small next to the letter (e.g. "A UF-UR").
  caseSecondary: (c) => c.path[1].split(SEP).join('-'),
  statsDisplay: (c, toLetter) => ({
    primary: toLetter(c.path[2]),
    secondary: `${c.path[0]} ${c.path[1].split(SEP).join('-')}`,
  }),
  statsGroupFilter: true,
}
