import type { AlgCase, Algset } from '@/algsets/types'
import type { ToLetter } from '@/helpers/helpers'
import { SPEFFZ } from '@/algsets/commutators'

// T2C: LTCT cases of the non-UFR buffers whose twisted corner is UFR — the
// situation "two corners left + your buffer is twisted". Solved as a 3-target
// sequence X Y X' from the next buffer, where both X-targets sit on the same
// corner (data: t2c_map.json, generated by scripts/fetch_blddb_algs.mjs from
// blddb's ltctManmade.json).
export interface RawT2c {
  corners: [string, string] // the two case corners (canonical sticker names)
  twist: string // UFR twist sticker (RUF = cw, FUR = ccw)
  variants: Record<string, string[]> // start sticker -> full 3-target memo
  algs: string[]
}

// Corner stickers in clockwise order starting from the U/D facelet (same
// table as CORNER_CYCLES in scripts/fetch_blddb_algs.mjs).
const STICKER_CYCLES = [
  ['UFR', 'RUF', 'FUR'],
  ['UFL', 'FUL', 'LUF'],
  ['UBL', 'LUB', 'BUL'],
  ['UBR', 'BUR', 'RUB'],
  ['DFR', 'FDR', 'RDF'],
  ['DFL', 'LDF', 'FDL'],
  ['DBL', 'BDL', 'LDB'],
  ['DBR', 'RDB', 'BDR'],
]

// sticker -> canonical corner name (the corner's U/D facelet)
export const CORNER_OF: Record<string, string> = {}
for (const cycle of STICKER_CYCLES) {
  for (const s of cycle) CORNER_OF[s] = cycle[0]
}

// Path segments join the memo stickers with this separator so each target
// translates independently through the letter scheme (like the comm sets).
const SEP = '·'

const lettersOf = (segment: string, toLetter: ToLetter): string =>
  segment.split(SEP).map(toLetter).join('')

// The memo starts at the first buffer sticker (settings order) that lies on
// one of the two case corners — that buffer's corner is "corner X". Cases
// whose corners carry no configured buffer (e.g. DBR+DBL with the default
// order) fall back to blddb's canonical representation (corners[0]).
export const chooseStart = (c: RawT2c, bufferOrder: string[]): string => {
  for (const b of bufferOrder) {
    const corner = CORNER_OF[b]
    if (corner && corner !== 'UFR' && (corner === c.corners[0] || corner === c.corners[1])) {
      return b
    }
  }
  return c.corners[0]
}

export const partition = (raw: Record<string, RawT2c>, bufferOrder: string[]): AlgCase[] => {
  const rank = new Map(bufferOrder.map((b, i) => [CORNER_OF[b], i]))

  type Sortable = AlgCase & { _sort: [number, string] }
  const out: Sortable[] = []

  for (const [id, c] of Object.entries(raw)) {
    const start = chooseStart(c, bufferOrder)
    const memo = c.variants[start]
    if (!memo) continue // data/settings mismatch; skip rather than crash
    out.push({
      id,
      path: [CORNER_OF[start], memo.join(SEP)],
      algs: c.algs,
      scrambles: [], // none pre-generated; makeScramble falls back to inverse algs
      _sort: [rank.get(CORNER_OF[start]) ?? bufferOrder.length, memo.map((s) => SPEFFZ[s] ?? s).join('')],
    })
  }

  out.sort((a, b) => a._sort[0] - b._sort[0] || a._sort[1].localeCompare(b._sort[1]))
  return out.map(({ _sort, ...rest }) => rest)
}

export const t2c: Algset = {
  id: 't2c',
  name: 'algset.t2c',
  usesLetterScheme: true,
  levels: [
    // Stufe 1: corner X in piece notation, with its letter as secondary.
    { id: 'corner', display: (v, ctx) => ({ primary: v, secondary: ctx.toLetter(v) }) },
    { id: 'case', display: (v, ctx) => ({ primary: lettersOf(v, ctx.toLetter) }) },
  ],
  load: () =>
    import('@/assets/t2c_map.json').then(
      (m) => (m.default as unknown) as Record<string, RawT2c>,
    ),
  derive: (raw, deps) => partition(raw as Record<string, RawT2c>, deps.bufferOrder),
  caseLabel: (c, toLetter) => lettersOf(c.path[c.path.length - 1], toLetter),
  // The full memo in piece notation, e.g. "UFL-DFL-LUF".
  caseSecondary: (c) => c.path[1].split(SEP).join('-'),
  statsDisplay: (c, toLetter) => ({
    primary: lettersOf(c.path[1], toLetter),
    secondary: c.path[0],
  }),
  statsGroupFilter: true,
}
